Services/LegalDocuments
iszmais/ILIAS pull request #1
Opened 2023-10-17 16:29 UTC by lscharmer

Add new Service LegalDocuments, implement TermsOfService and DataProtection.

2023-10-18 13:20 UTC, iszmais requested changes
Mostly looks good to me. 4 Major points beside the singel threads:

- This still includes a lot of commented code var_dmps and todos. Pls ensure if this is still needed/helpfull. If you want to preserve Code i encourage you to do that extarnalt e.g. by appending a file to your PR. otherwise this might become forgotten.
- You sometimes use the legacy component of the UI factory just to present a kind of list. Pls reconsider the usage of other components for that. Lagecy is not deprecated in any way but should only be used if the is no other option.
- Some of your pathes (mostly inside the tests) have double slashes. Pls reduce them to single ones.

Optional you may also reevalue the usage of the `class.` prefix for some files. I know its still a thing for UI but im not sure if its required for other files.

2023-10-18 13:20 UTC, iszmais commented on Services/Awareness/User/class.Collector.php
> +        $remove_users = array_merge($remove_users, $DIC['legalDocuments']->usersWithHiddenOnlineStatus($all_users));
This does nothing.

2023-10-18 13:20 UTC, iszmais commented on Services/DataProtection/classes/class.ilObjDataProtectionGUI.php
> +
Pls add license header

2023-10-18 13:20 UTC, iszmais commented on Services/DataProtection/classes/class.ilObjDataProtectionGUI.php
> +
Pls add license header

2023-10-18 13:20 UTC, iszmais commented on Services/DataProtection/classes/class.ilObjDataProtectionGUI.php
> +
Pls add license header

2023-10-18 13:20 UTC, iszmais commented on Services/DataProtection/classes/class.ilObjDataProtectionGUI.php
> +
Pls add license header

2023-10-18 13:20 UTC, iszmais commented on Services/DataProtection/classes/class.ilObjDataProtectionGUI.php
> +        $DIC->language()->loadLanguageModule('tos');
Why not use $this->container instead of global DIC?

2023-10-18 13:20 UTC, iszmais commented on Services/Hui/artifacts/consumers.php
> +);
pls add a new line at the end and a new line before return

(optional: also  add the strict types and license header)

2023-10-18 13:20 UTC, iszmais commented on Services/Init/classes/class.ilInitialisation.php
> +        $c['legalDocuments'] = static fn (\ILIAS\DI\Container $c) => new \ILIAS\LegalDocuments\Conductor($c);
Pls use `use` instead of full pathing

2023-10-18 13:20 UTC, iszmais commented on Services/Init/classes/class.ilStartUpGUI.php
> +            $DIC['legalDocuments']->loginPageHTML(),
If not already existing you mifght consider adding a wrapper function to the container to call the legalDocuments like `$DIC->legalDocuments()`

2023-10-18 13:20 UTC, iszmais commented on Services/Init/classes/class.ilStartUpGUI.php
> +        global $DIC, $tpl;
Pls dont call global variables that are allready inside the called DIC (like tpl, ilUser, ....).

In case here $tpl isnt used anyways afaik.

2023-10-18 13:20 UTC, iszmais commented on Services/LegalDocuments/artifacts/consumers.php
> +);
Pls add newc lines at the end and before `return`.

You may also add strict type and license header

2023-10-18 13:20 UTC, iszmais commented on Services/LegalDocuments/classes/Config.php
> +    public function allowEditing(): self
Since This seems to be imutable i would prefer to follow the ilias convetion for such functions and call it `withEditing`

2023-10-18 13:20 UTC, iszmais commented on Services/LegalDocuments/classes/Content.php
> +
Pls add license header

2023-10-18 13:20 UTC, iszmais commented on Services/LegalDocuments/classes/HandyConsumerTools/Blocks.php
> +    public function retrieveQueryParameter(string $key, Closure $select)
Kann you maybe make an assumption for the return type hee based on the context?

2023-10-18 13:20 UTC, iszmais commented on Services/LegalDocuments/classes/HandyConsumerTools/ConsumerSlots/ShowOnLoginPage.php
> +    /**
pls add a newline here

2023-10-18 13:20 UTC, iszmais commented on Services/LegalDocuments/classes/Provide/ProvideDocument.php
> +    public const CRITERION_WOULD_NEVER_MATCH = 'Criterion would never match.';
Is this needed to be translated maybe?

2023-10-18 13:20 UTC, iszmais commented on Services/LegalDocuments/classes/Provide/ProvideWithdrawal.php
> +
remove line

2023-10-18 13:20 UTC, iszmais commented on Services/LegalDocuments/classes/Repository/NiceFields.php
> +trait NiceFields
Pls reconsider the name of that trait. Beside the risky decision to use adjectives within the naming system, these should never of a judgemental kind but only functional (like acceptable are `upper` `lower` `complex` `decorated` `basic` `advanced` ... . Critical are `nice` `bad` `pointless` `better` `easy` ...). However there may be some exceptions for established keywords like `lazy`.

But in general we are inclusive and dont want other traits to feel bad or left out :heart:

2023-10-18 13:20 UTC, iszmais commented on Services/LegalDocuments/classes/Setup/Agent.php
> +
pls add license header

2023-10-18 13:20 UTC, iszmais commented on Services/LegalDocuments/classes/Setup/ConsumerObjective.php
> +
license header

2023-10-18 13:20 UTC, iszmais commented on Services/LegalDocuments/classes/class.ilLegalDocumentsAdministrationGUI.php
> +    private function criterionInvalid($error): Result
The return here can specified as `OK` instead of `Result`.

2023-10-18 13:20 UTC, iszmais commented on Services/LegalDocuments/classes/class.ilObjLegalDocuments.php
> +
license header

2023-10-18 13:20 UTC, iszmais commented on Services/LegalDocuments/maintenance.json
> +    "first_maintainer": "lscharmer",
Pls add your ILIAS doc id to your name like `lscharmer(87863)`

2023-10-18 13:20 UTC, iszmais commented on Services/UICore/classes/class.ilCtrl.php
> +
pls remove line (to exclude file from changes)

2023-10-18 13:20 UTC, iszmais commented on Services/User/Profile/classes/class.ilPersonalProfileGUI.php
> +<?php
This class seems a bit out of place here...
Do you wanted to add it?

2023-10-18 13:20 UTC, iszmais commented on Services/User/classes/class.ilObjUserFolderGUI.php
> +                    (string) ((int) $this->form->getInput('tos_withdrawal_usr_deletion'))
I assume you expecting to return `0` or `1` here therefore i would encourage your to transform the input instzead of casting it to ensure unity, like:
`($this->form->getInput('tos_withdrawal_usr_deletion') === '1') ? '1' : '0'`

2023-10-18 13:20 UTC, iszmais commented on Services/User/classes/class.ilUserAppEventListener.php
> +            global $DIC;
This Block doesnt make sense

2023-10-18 13:20 UTC, iszmais commented on lang/ilias_en.lang
> +dpro#:#dpro_account_reg_not_possible#:#Self-registration is currently not possible because there is no Data Protection agreement available. Please contact your <a href="%1$s">system administrator</a>
This is a duplication of the previous

2023-10-18 13:20 UTC, iszmais commented on lang/ilias_en.lang
> +dpro#:#dpro_sure_reset_tos#:#Are you sure you want to reset the Data Protection for all users in the system? This also applies, for example, to those accounts that are used for the SOAP web services.
This is a duplication of the previous

2023-10-18 13:20 UTC, iszmais commented on src/Data/Factory.php
> +        if (is_int((string) $size) && (is_null($unit) || !array_key_exists((string) $unit, DataSize::$abbreviations))) {
This is always false

2023-10-18 13:20 UTC, iszmais commented on src/Refinery/ByTrying.php
> +    private $lng;
is not used

2023-10-18 13:20 UTC, iszmais commented on Services/Contact/build/dox.html
> +            <li style="color: #555753;">✓ Elements can be initially added with data set "indexed"</li>
Pls append the coloring to the style tag instead of inline on evry `li`.

2023-10-18 13:20 UTC, iszmais commented on Services/Contact/build/dox.html
> +</html>
Pls add new line

2023-10-18 15:12 UTC, lscharmer commented on Services/LegalDocuments/classes/HandyConsumerTools/Blocks.php
> +    public function retrieveQueryParameter(string $key, Closure $select)
No, it could be anything

2023-10-18 15:18 UTC, lscharmer commented on Services/LegalDocuments/classes/Provide/ProvideDocument.php
> +    public const CRITERION_WOULD_NEVER_MATCH = 'Criterion would never match.';
They are translated. I could just as well have written `const CRITERION_ALREADY_EXISTS = 'CRITERION_ALREADY_EXISTS'`. The content of these values do not matter.

2023-10-19 13:07 UTC, lscharmer commented on Services/Awareness/User/class.Collector.php
> +        $remove_users = array_merge($remove_users, $DIC['legalDocuments']->usersWithHiddenOnlineStatus($all_users));
Yes, it does.

2023-10-19 13:27 UTC, closed without merging