Moved to Notification-Scope
iszmais/ILIAS pull request #7
Opened 2022-12-13 13:00 UTC by chfsx

Hi @iszmais 

Ich habe gedacht es geht am schnellsten, wenn ich das direkt kurz verschiebe: Ich sehe die Toasts nicht als eigenen Scope, habe sie daher in den Scope der Notifications verschoben, dabei aber als eigenständige Providers und Collectors belassen.

Ansonsten habe ich versucht das Collecten etc. alles schon zu implementieren, auch so, dass plugins das direkt auch nutzen können.

Der PR hier ist ungetestet, ich weiss nicht, ob damit dein Einsatzzweck noch funktioniert, das müsstest du kurz ausprobieren :-) Wenn du hier mergest, wird der PR im ILIAS-Repo ja dann aktualisiert. Gerne dort aber dann auch noch einige UnitTest beisteuern, das wäre super!

2022-12-13 15:28 UTC, iszmais commented
Hallo @chfsx ,
Kannst du genauer erläutern warum du die Toast nicht als eigenen Scope siehst?
M.E. gibt es schon Anwendungsfälle auserhalb der Notifciations und es werden in Zukunft sicherlich einige Anforderungen an die Toasts enstehen die nicht zwingend etwas mit den Notifications zu tun haben.

Aktuell würden mir da z.b. "WhoIsOnline" einfallen, welches ja momentan aus ermangelung an Alternativen einen Notfication Provider stellt, aber im Kern eigentlich  nichts mit den Notfications zutun hat. (Also es interagiert nicht mit dem NC ist nicht aysncron und erzeugt bei jedem Request einen neue "Notifcation" und löscht alle alten).
Dieses Verhalten ließe sich in den Tool deutlich einfacher und intuitiver umsetzen, ohne Workarounds etc.
Nur um ein Aktuelles beispiel zu nennen.

Und generell ließe sich der Toast für nicht persistente Stati und zeitrelevante Aussagen gut nutzen.
Besonders da im Refactoring der Notifications deren persitens nochmal strikter definiert wurde.

Daher würde ich einen eigenen Scope vorziehen.

Freundliche Grüße,
@iszmais

2022-12-13 15:28 UTC, iszmais commented
FYI @mjansenDatabay @lscharmer

2022-12-14 11:03 UTC, iszmais commented
Hallo @chfsx ,
Danke für den Diskurs!
Ich habe mich bezüglich der genannten Argumente auch nochmal mit ein paar mir überlegenen Leuten aus Entwicklung und Desgin zusammengesetzt um ggf. meinen Denkfehler darin zu erkennen. Allerdings erschließt sich mir die Argumentation noch nicht ganz bezüglich der Erweiterbarkeit der Scopes:
- Zum einen hat sich m.E. seit der implementierung der Scopes, die ja auch konzeptionelle Auswirkungen auf die Definition von Notifications hatte, einiges geändert sodass ich diese Teile als disjunkt betrachten würde. So sind Notification m.E. ein persitenter Bestanteil der ILIAS Organisationsstruktur (Wie z.b. Mails, Backgroundtasks, Invitations) wärend Toast innerhalb der Struktur eine flüchtige Komponente innerhalb eines nonpersitenten Overlays darstellen (Online stati, Alerts, Income-Messages). Daher sehe ich sie näher an den Statusmeldungen der Modalen als an den Notifications. Die Einzige Verbindung diebzüglich liegt meines erachtens in der gemeinsamen Historie, die aber ja aus einem guten Grund refactored wurde.
- Desweitere bin ich natürlich auch an der Erweiterbarkeit des Systems interessiert und weiß um die skalierung digitaler Anwendungen, allerdings erschließt sich mir kein Szenario in dem auch nur Annähernd eine weite von 200 Scopes erreicht werden kann. Es kann sein das ich diesbezüglich den Begriff "Scope" falsch definiere, ggf. kannst du mir da nochmal erläutern, allerdings würde es mir schwer fallen selbst sehr kleinstrukturiert auf einen vollkommen überladenen Seite mehr als 20 Scopes zu definieren. Ich habe mich diesbezüglich auch nochmal mit unserem Designteam verständigt und wir sind dort auf einen Nenner gekommen. Zumal die Entwicklung in diesem Bereich ja auch nicht Exponentiel oder linear steigend ist sondern tendentiell er zurückgeht. Und selbst wenn ich mir die schrecklichen Multitool seiten der jungen 2000er in Erinnerung rufe (Stichwort: Facebook) sehe ich da nicht mehr als vielleicht 12 Scopes o.ä.
- Und zuletzt  selbst wenn ILIAS das unmögliche gelingen sollt und wir 200 Scopes implementiert bekommen denke ich nicht das eine verschachtlung der Scopes der (dann sowieso schon sehr unübersichtlichen) Struktur helfen würde. m.E. sucht man dann nur eine Ebene tiefer. Allerdings kann ich die kritik durchaus verstehen den Toast nicht zu einem "Über"-Scope zu machen. Ggf. könnte man ansonsten eine Gruppe für derartige Objekte einrichten, z.b. einen "Overlay" Scope, in den dan in Zukunft auch ähnliche komponentnen Einsortiert werden können.

Ich würde mich freuen deine Meinung dazu zu hören.
Ich hatte auch schon überlegt ob das ggf. etwas für den JourFixe sein könnte, besonders da ja einige Entwickler von diesen Changes betroffen wären. Und egal welche Lösung es am Ende wird wäre es vermutlich eh gut hier ein bisschen Awarness zu spreaden damit jeder der diese Komponente bzw. deren Provider in Zukunft nutzen möchte dazu schonmal was gehört hat.
Gerne auch da deinen Meinung dazu.

Freundliche Grüße,
@iszmais

2023-02-01 07:29 UTC, chfsx commented
Hi! wie eben geschrieben müssten die beiden Commits hier noch gemerged werden, danach merge ich dann deinen PR in release_8 (mit Squash) und cherry-picke das dann in trunk. Vielen Dank für die Diskussion und deine Arbeit!

2023-02-01 10:20 UTC, iszmais requested changes
Hi @chfsx ,

danke für das strukturierte Review!
Eine Kleinigkeit noch vor dem merch: Wenn ich mich nicht täusche müsste die Zeile `declare(strict_types=1);` von dem License Header stehen also
```
<?php

declare(strict_types=1);

/**
``` 

Zumindest wird  es so im copyright-checker.sh erwartet (sofern mich meine Script kenntnisse nicht täuschen).

2023-02-01 10:28 UTC, chfsx commented
Ich bin mir ziemlich sicher, dass man das vor kurzem angepasst hat, ich habe darauf auch mein script anpassen müssen, das mir den license-header automatisch an die richtige stelle setzt. bin grad am suchen, wann diese änderung kam.... bei mir nörgelt der checker zumindest nicht so

2023-02-01 10:34 UTC, chfsx commented
Also nach dem License-Header: https://discord.com/channels/819582183290437642/938352958876286988/1070290923440848896 `gem. PSR-12 ist der license-header ein file-level kommentar und die declare statements sollen erst danach folgen.`

2023-02-01 10:53 UTC, iszmais commented
Ah ok das kannte ich noch nicht ^^

2023-02-01 10:53 UTC, merged